CREATE TABLE users (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    city VARCHAR(50)
);

CREATE TABLE products (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10,2)
);

CREATE TABLE orders (
    id INT PRIMARY KEY,
    user_id INT,
    product_id INT,
    quantity INT,
    order_date DATE,
    
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE QUERY_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUESTION VARCHAR(1000) NOT NULL,
    SQL_QUERY VARCHAR(5000) NOT NULL,
    OPERATION_TYPE VARCHAR(20),
    SUCCESSFUL BOOLEAN NOT NULL,
    EXECUTION_TIME_MS BIGINT,
    TIMESTAMP TIMESTAMP NOT NULL
);